import type { Metadata } from "next";
import { Montserrat, Press_Start_2P } from "next/font/google";
import NextTopLoader from 'nextjs-toploader';
import { ThemeProvider } from "@/components/theme-provider"
import Header from "@/components/Header";
import Image from "next/image";
import "./globals.css";

const montserrat = Montserrat({ 
  subsets: ['latin'],
  variable: '--font-montserrat',
  display: 'swap',
});

const pressStart2P = Press_Start_2P({ 
  weight: '400',
  subsets: ['latin'],
  variable: '--font-press-start-2p',
  display: 'swap',
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={`${montserrat.variable} ${pressStart2P.variable}`}>
      <head />
      <body className={`${montserrat.className} overflow-x-hidden`}>
        <NextTopLoader color="var(--red)" showSpinner={false} />
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
          <Header />
          <div className="mt-45 relative">
            <Image className="fixed rotate-[30deg] -z-50 opacity-5 dark:opacity-10 right-0 -top-50 grayscale" src="/pokedex.svg" alt="dex-bg" width={1200} height={30} />
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
